import Graph from './lib/graph.class.js'

const cidades = new Graph(false)

// Conexões entre cidades (sem considerar distâncias)
cidades.addEdge('Igarapava', 'Ituverava')
cidades.addEdge('Igarapava', 'Rifaina')
cidades.addEdge('Igarapava', 'Jeriquara')
cidades.addEdge('Ituverava', 'Jeriquara')
cidades.addEdge('Ituverava', 'Guará')
cidades.addEdge('Guará', 'São Joaquim da Barra')
cidades.addEdge('Guará', 'Ribeirão Corrente')
cidades.addEdge('São Joaquim da Barra', 'São José da Bela Vista')
cidades.addEdge('Ribeirão Corrente', 'Franca')
cidades.addEdge('Ribeirão Corrente', 'Jeriquara')
cidades.addEdge('São José da Bela Vista', 'Franca')
cidades.addEdge('Franca', 'Restinga')
cidades.addEdge('Franca', 'Cristais Paulista')
cidades.addEdge('Franca', 'Claraval')
cidades.addEdge('Franca', 'Ibiraci')
cidades.addEdge('Cristais Paulista', 'São José da Bela Vista')
cidades.addEdge('Cristais Paulista', 'Pedregulho')
cidades.addEdge('Pedregulho', 'Rifaina')
cidades.addEdge('Claraval', 'Ibiraci')
cidades.addEdge('Itirapuã', 'Patrocínio Paulista')
cidades.addEdge('Patrocínio Paulista', 'Franca')
cidades.addEdge('Patrocínio Paulista', 'Batatais')
cidades.addEdge('Restinga', 'Batatais')
cidades.addEdge('Franca', 'Batatais')
export default cidades
